### PR TITLE
Fix rounding of datatypes

### PR DESCRIPTION
**Pull request by fdw**
Sometimes, precipitation chance is shown with a lot of decimals. Since this is only annoying and doesn't contain a lot of sensible information, let's round it.

I've tried to implement it myself, but it's my first time doing Rust. So, if you find anything weird or bad, please change it 🙂
Also, I've tried to run the tests, but they always hang on `no_api_key`, even on `master`. So I expect this to work, but please make sure!

### CODE REVIEW

**Comment by awersching** [comment]
Good idea, thank you! I'll have a look at it as soon as I can.

**Comment by fdw** [comment]
Thanks you!

If you have time, and just out of curiosity because I'm very new to Rust: Do you have any tips what I could've done better regarding the code itself? :)

**Comment by awersching** [comment]
I just though using [std::fmt](https://doc.rust-lang.org/stable/std/fmt/) was more self-explanatory that's all

**Comment by fdw** [comment]
Thank you 🙂

**Pull request merged**
